@@startuml BE-exercise-architecture
top to bottom direction
' left to right direction 

skinparam {
    ' Nodesep 5
    ' Ranksep 5
    Linetype ortho
    layout GEM 
}

cloud {
    component "API Client" as [Client]
}

package "BE Code Exercise" as [App] {
    component "API Routes" as [API]
    ' component "Controllers" as [Contr]
    component "Json Views" as [View]
    component "Ecto Models" as [Model]
    component "Cache Layer" as [Cache]



    frame "Controller APIs" as [Contr] {
        component [Employee]
        component [Country]
        component [Currency]
    }
}

package "DB" {
    database "PostgreSQL" {
        [Currencies]
        [Countries]
        [Employees]
    }
}
'API & clients
[Client] --> [API]
[View] --> [Client]

' APP
[API] --> [Contr]
' fetches and stores data in cache
[Employee] <--> [Cache]

[Contr] <--> [Model]
[Contr] -u-> [View]

'APP to DB
[Model] <--> [PostgreSQL]

'hidden arrows for layout
[App] -[hidden]d-> [DB]
[Client] -[hidden]d-> [App]

' DB relationships
[Countries] -r-> [Employees] : " 1:M "
[Currencies] -r-> [Countries] : " 1:M "


@@enduml