services:
  postgres:
    image: postgres:16.2-alpine
    container_name: be-exercise-postgres-test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: be_exercise_test
    ports:
      - "127.0.0.1:5432:5432"

